name: CatatclysmBar
version: 1.0.1
main: me.elyndor.fakebar.CatatclysmBar
api-version: "1.20"

softdepend:
  - PlaceholderAPI
  - AuraSkills

commands:
  ccb:
    description: CatatclysmBar control command
    usage: /ccb <reload|on|off>
    permission: catatclysmbar.admin

permissions:
  catatclysmbar.admin:
    default: op
