name: Build CatatclysmBar

on:
  push:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Build CatatclysmBar
        run: mvn -B clean package

      - name: Upload CatatclysmBar JAR
        uses: actions/upload-artifact@v4
        with:
          name: CatatclysmBar-1.0.1
          path: target/CatatclysmBar-1.0.1.jar
